"""empty message

Revision ID: 3da3112ce2d9
Revises: None
Create Date: 2015-08-25 23:52:08.321608

"""

# revision identifiers, used by Alembic.
revision = '3da3112ce2d9'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
